### PR TITLE
ci: Use latest upstream kernel and exclude scx_flatcg and scx_pair from testing

### PR DESCRIPTION
**Pull request by htejun**

### CODE REVIEW

**Review by arighi — APPROVED** [review]

**Review by arighi — COMMENTED** [review]
Just noticed that we also need to fix vng to get the .config chunk from the scx repo, since we don't have the .github dir anymore in the kernel from korg.

**Comment by htejun** [comment]
Ah, that's what's missing. Would you mind to commandeer the commit?

**Comment by arighi** [comment]
> Ah, that's what's missing. Would you mind to commandeer the commit?

yep, will fix this in a bit.

**Comment by htejun** [comment]
Thank you.

**Comment by arighi** [comment]
@htejun f72e7567bfb3acab2b82dacb94de13d7ccf4a52e should fix it

**Comment by htejun** [comment]
Oh, please do a new PR. I'll abandon this one. Thank you.

**Pull request closed without merging**
