### PR TITLE
scx: set rust to stable

### PR DESCRIPTION
**Pull request by likewhatevs**
set rust version to stable and remove rustfmt.toml files (these were all the same and were the reason we were depending on nightly rust afaik).

also run fmt so lint job passes

### CODE REVIEW

**Review by htejun — APPROVED** [review]

**Review by ruihe774 — CHANGES_REQUESTED** [review]
IMO it'll be better to also set the Rust toolchain used in CI to stable.

**Comment by likewhatevs** [comment]
> IMO it'll be better to also set the Rust toolchain used in CI to latest stable.

this is the toolchain used in CI.

**Review by ruihe774 — APPROVED** [review]

**Comment by likewhatevs** [comment]
Actually, I think I see what you are saying, let me explain.

So like, rust-toolchain ensures that for our code, the rust toolchain used will be the specified one.

On ci, when nightly is set to default, it makes everything else outside of that "just work". For example, doc generation or installing system-ish packages which may depend upon that. That's why there is rustup default nightly in the dependency install script.

**Comment by ruihe774** [comment]
> Actually, I think I see what you are saying, let me explain.
> 
> So like, rust-toolchain ensures that for our code, the rust toolchain used will be the specified one.
> 
> On ci, when nightly is set to default, it makes everything else outside of that "just work". For example, doc generation or installing system-ish packages which may depend upon that. That's why there is rustup default nightly in the dependency install script.

Do we ensure that the code can be built with stable in CI? If there is already such test, I think it's okay.

**Pull request merged**
