### PR TITLE
scx_rustland: cpu topology refactoring

### PR DESCRIPTION
**Pull request by arighi**
Introduce the concept of core (as a set of CPUs) in scx_utils::Topology and get rid of the custom CPU topology abstraction in scx_rustland.

Same functionality, but with less code:
```
 3 files changed, 54 insertions(+), 111 deletions(-)
```

### CODE REVIEW

**Comment by Decave** [comment]
@arighi FYI, I have a big refactor that I'm working on and planning on sending out shortly: https://github.com/sched-ext/scx/tree/topology_refactor. I'm fine with landing this and then applying the changes to scx_rustland, if that's OK with you.

**Comment by arighi** [comment]
> @arighi FYI, I have a big refactor that I'm working on and planning on sending out later today: https://github.com/sched-ext/scx/tree/topology_refactor. I'm fine with landing this and then applying the changes to scx_rustland, if that's OK with you.

No problem. Whatever you prefer, if this change is conflicting with yours feel free to drop it and I'll adjust it after the new refactoring is merged.

**Comment by Decave** [comment]
> > @arighi FYI, I have a big refactor that I'm working on and planning on sending out later today: https://github.com/sched-ext/scx/tree/topology_refactor. I'm fine with landing this and then applying the changes to scx_rustland, if that's OK with you.
> 
> No problem. Whatever you prefer, if this change is conflicting with yours feel free to drop it and I'll adjust it after the new refactoring is merged.

Ok, thanks. Given that it's essentially a total rewrite of the crate, is it OK if we merge https://github.com/sched-ext/scx/pull/154 (assuming there are no issues)? I can take care of cleaning up `scx_rustland` to use it after it lands.

**Comment by arighi** [comment]
Sure, go for it!

**Comment by arighi** [comment]
Sure, go for it!

**Comment by Decave** [comment]
Sent out https://github.com/sched-ext/scx/pull/155 which updates `scx_rustland` to use the new Topology crate.

**Comment by Decave** [comment]
https://github.com/sched-ext/scx/pull/155 was merged, so we can close this out.

**Pull request closed without merging**
