### PR TITLE
scx: add ci job to test rolling stable

### PR DESCRIPTION
**Pull request by likewhatevs**
scx: add ci job to test rolling stable

this should run every 4 hours

will merge once I see this run on my fork, should just work (err well just fail because I think this is broke atm).

@ptr1337

### CODE REVIEW

**Comment by ptr1337** [comment]
Thanks for adding this!
I think it would be quite good to test again the stable-rc branch, or?

**Review by arighi — APPROVED** [review]

**Comment by arighi** [comment]
Thanks for doing this, feel free to merge when it works

**Comment by likewhatevs** [comment]
> I think it would be quite good to test again the stable-rc branch, or?

tbh I just picked the one that sounded right, let me look into what the branches are and confirm it is the right one. we want to build against the equivalent of for-next so that we are aware of breakages before they get cut into a release.

**Comment by likewhatevs** [comment]
I'm not certain there's anything better to use than `linux-rolling-stable`, but am open to suggestions if anyone has one.

Looking at:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git

It looks like commits are pushed the same time as they are to `linux-stable-rolling`.

**Review by htejun — APPROVED** [review]

**Pull request merged**
