### PR TITLE
bump libbpf-rs version to 0.24.8, specify libbpf-sys version 1.4.6+1.4.7

### PR DESCRIPTION
**Pull request by etsal**
This is  a redo of #1087 which was accidentally closed.

### CODE REVIEW

**Comment by likewhatevs** [comment]
I think you need to remove the revert commit to make this do what is intended (no changes atm).

**Review by likewhatevs — APPROVED** [review]
signals are solid wrt/ what this touches, once green lets do it.

**Comment by etsal** [comment]
> I think you need to remove the revert commit to make this do what is intended (no changes atm).

Oh yeah, I added a revert commit to try to see whether the CI breakage we were seeing was caused by the commit or if it was an issue with the ppas.

**Comment by likewhatevs** [comment]
Ahh btw, because we're using head of the sched_ext repo on kernel.org, main is built hourly to help us see issues like this one (i.e. if you ever suspect that, just check CI status on main, it'll be red if that's the case).

**Review by htejun — APPROVED** [review]

**Pull request merged**
