### PR TITLE
scx_rustland: handle graceful vs non-graceful exit

### PR DESCRIPTION
**Pull request by arighi**
Do not report an exit error message if it's not present. Moreover, distinguish between a graceful exit vs a non-graceful exit.

NOTE: in the future the whole exit handling probably can be moved to a more generic place (scx_utils) to prevent code duplication across schedulers and also to prevent small inconsistencies like this one.

### CODE REVIEW

**Comment by arighi** [comment]
Hm... actually I'm not sure about this change, it looks like other schedulers are doing different checks. For example `scx_layered` is doing `if etype != 64 ` to determine if we need to print a message, `scx_rusty` is doing this check. The C schedulers instead are checking if the message is empty (in `uei_print()`).

Looking at the kernel code it seems that we may want to print the message if `etype >= 64`, that seems to be the limit between graceful and non-graceful exits.

What is the correct API?

**Comment by arighi** [comment]
Pushed another version that makes more sense, or at least it seems more consistent with the kernel's `scx_exit_kind` values.

**Comment by htejun** [comment]
Following what user_exit_info.h is doing is probably the best. Can you please update accordingly? Thanks.

**Comment by arighi** [comment]
I will include this change in a new PR with more improvements for scx_rustland, closing this one for now.

**Pull request closed without merging**
