### PR TITLE
scx_layered Fix trace format

### PR DESCRIPTION
**Pull request by hodgesds**
😭

### CODE REVIEW

**Review by htejun — APPROVED** [review]

**Comment by likewhatevs** [comment]
keep saying to copy my vimrc lol
CleanShot 2024-11-01 at 15 47 42@2x

**Review by likewhatevs — APPROVED** [review]

**Comment by likewhatevs** [comment]
> Honestly, we need to change the BPF building system to report Clang warnings in the Rust build output. Easy way would be turning on -Werror, but it should be totally possible to emit them as warnings from Cargo.

Not a fan of this *but* it gives me an idea I think might be good. 

I think we could use the clangd config to ahh have a shell script compile all the main.bpf.c files with werror. An added benefit would be CI would fail whenever folks add files w/o making includes etc. work with LSP (huge fan of this, pay the build tax when adding files). 

This might sound like churn for idk non-goal thing (devexp for folks using idk lsp etc.), *but* it maps legit incrediblty well to how well code can be moved to alternative build systems (i.e. the same things that choke that config or LSP choke other build systems).

> We can't expect everybody to run and pay attention to clangd which requires custom setup to work right with BPF to catch things like this.

Ahh pretty sure if this repo is opened in something batteries included (like vscode) with a clangd extension everything "just works" (because the config is in the repo here).

**Comment by JakeHillion** [comment]
> > Honestly, we need to change the BPF building system to report Clang warnings in the Rust build output. Easy way would be turning on -Werror, but it should be totally possible to emit them as warnings from Cargo.
> 
> Not a fan of this _but_ it gives me an idea I think might be good.

How come you're not a fan? If someone causes a Rust warning they see it when they build, and if you're in a normal C project you see C warnings when you build. I don't see any benefit here to hiding the Clang warnings - it feels more like an implementation accident.

> I think we could use the clangd config to ahh have a shell script compile all the main.bpf.c files with werror. An added benefit would be CI would fail whenever folks add files w/o making includes etc. work with LSP (huge fan of this, pay the build tax when adding files).

`-Werror` on the CI but not on local builds feels a bit weird to me, but it would solve any consistency issues we have between the clang versions people use on their local boxes & a single CI source of truth for errors. Definitely not vetoing it.

> This might sound like churn for idk non-goal thing (devexp for folks using idk lsp etc.), _but_ it maps legit incrediblty well to how well code can be moved to alternative build systems (i.e. the same things that choke that config or LSP choke other build systems).

ACK. As long as we're not getting spurious warnings this doesn't feel like a non-goal at all, `-Werror` is good generally and if it solves the LSP breaking as a side effect that's totally fine by me.
 
> > We can't expect everybody to run and pay attention to clangd which requires custom setup to work right with BPF to catch things like this.
> 
> Ahh pretty sure if this repo is opened in something batteries included (like vscode) with a clangd extension everything "just works" (because the config is in the repo here).

True, but we shouldn't require people to have a full IDE setup in order to not "break" the repo, whether that be because they didn't get a warning or because we expect LSPs to work in the repo. Simple text changes and a build should definitely show you the warnings IMO, catching them in the CI is really too late for productivity.

**Comment by JakeHillion** [comment]
@likewhatevs `-Werror` isn't necessary, but we have to change the source of `libbpf-cargo` annoyingly. I got this output to come out pretty easily. Note that the build succeeded, these are warnings, and it's made very clear that the entire output of the `clang` command is a warning if it didn't fail. Also note that schedulers which don't have any warnings are no more verbose than before. To me, whose workflow is write code & build, this is perfectly useful. Sure it doesn't have the pretty colours I get if I run clang manually, but they're the real warnings from the clang build and I can fix them.

```
warning: /data/users/jakehillion/scx/rust/scx_rustland_core/Cargo.toml: unused manifest key: lib.include
warning: scx_layered@1.0.5: src/bpf/main.bpf.c:878:1: warning: unused label 'preempt_fail' [-Wunused-label]
warning: scx_layered@1.0.5:   878 | preempt_fail:
warning: scx_layered@1.0.5:       | ^~~~~~~~~~~~~
warning: scx_layered@1.0.5: src/bpf/main.bpf.c:2107:14: warning: format specifies type 'char *' but the argument has type 'int' [-Wformat]
warning: scx_layered@1.0.5:  2106 |                                 scx_bpf_dump("LAYER[%d][%s]DSQ[%d] nr_cpus=%u nr_queued=%d -%llums cpus=",
warning: scx_layered@1.0.5:       |                                                         ~~
warning: scx_layered@1.0.5:       |                                                         %d
warning: scx_layered@1.0.5:  2107 |                                              i, idx, layer->name, layer->nr_cpus,
warning: scx_layered@1.0.5:       |                                                 ^~~
warning: scx_layered@1.0.5: /data/users/jakehillion/scx/target/release/build/scx_layered-a2fb619f9daebb45/out/scx_utils-bpf_h/scx/common.bpf.h:150:43: note: expanded from macro 'scx_bpf_dump'
warning: scx_layered@1.0.5:   150 |     ___scx_bpf_bstr_format_checker(fmt, ##args);                               \
warning: scx_layered@1.0.5:       |                                    ~~~    ^~~~
warning: scx_layered@1.0.5: src/bpf/main.bpf.c:2107:19: warning: format specifies type 'int' but the argument has type 'char *' [-Wformat]
warning: scx_layered@1.0.5:  2106 |                                 scx_bpf_dump("LAYER[%d][%s]DSQ[%d] nr_cpus=%u nr_queued=%d -%llums cpus=",
warning: scx_layered@1.0.5:       |                                                                ~~
warning: scx_layered@1.0.5:       |                                                                %s
warning: scx_layered@1.0.5:  2107 |                                              i, idx, layer->name, layer->nr_cpus,
warning: scx_layered@1.0.5:       |                                                      ^~~~~~~~~~~
warning: scx_layered@1.0.5: /data/users/jakehillion/scx/target/release/build/scx_layered-a2fb619f9daebb45/out/scx_utils-bpf_h/scx/common.bpf.h:150:43: note: expanded from macro 'scx_bpf_dump'
warning: scx_layered@1.0.5:   150 |     ___scx_bpf_bstr_format_checker(fmt, ##args);                               \
warning: scx_layered@1.0.5:       |                                    ~~~    ^~~~
warning: scx_layered@1.0.5: src/bpf/main.bpf.c:136:12: warning: unused function 'llc_hi_fallback_dsq_iter_offset' [-Wunused-function]
warning: scx_layered@1.0.5:   136 | static u64 llc_hi_fallback_dsq_iter_offset(int llc_offset, int idx)
warning: scx_layered@1.0.5:       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: scx_layered@1.0.5: src/bpf/main.bpf.c:146:12: warning: unused function 'llc_iter_cpu_offset' [-Wunused-function]
warning: scx_layered@1.0.5:   146 | static int llc_iter_cpu_offset(int idx, s32 cpu)
warning: scx_layered@1.0.5:       |            ^~~~~~~~~~~~~~~~~~~
warning: scx_layered@1.0.5: 5 warnings generated.
warning: scx_lavd@1.0.5: src/bpf/main.bpf.c:1248:9: warning: incompatible pointer types assigning to 'struct task_struct *' from 'struct task_ctx *' [-Wincompatible-pointer-types]
warning: scx_lavd@1.0.5:  1248 |                 taskc = get_task_ctx(prev);
warning: scx_lavd@1.0.5:       |                       ^ ~~~~~~~~~~~~~~~~~~
warning: scx_lavd@1.0.5: src/bpf/main.bpf.c:1259:22: warning: incompatible pointer types passing 'struct task_struct *' to parameter of type 'struct task_ctx *' [-Wincompatible-pointer-types]
warning: scx_lavd@1.0.5:  1259 |                     is_lock_holder(taskc)) {
warning: scx_lavd@1.0.5:       |                                    ^~~~~
warning: scx_lavd@1.0.5: src/bpf/util.bpf.c:253:45: note: passing argument to parameter 'taskc' here
warning: scx_lavd@1.0.5:   253 | static bool is_lock_holder(struct task_ctx *taskc)
warning: scx_lavd@1.0.5:       |                                             ^
warning: scx_lavd@1.0.5: src/bpf/main.bpf.c:1383:44: warning: incompatible pointer types passing 'struct task_struct *' to parameter of type 'struct task_ctx *' [-Wincompatible-pointer-types]
warning: scx_lavd@1.0.5:  1383 |                         prev->scx.slice = calc_time_slice(prev, taskc);
warning: scx_lavd@1.0.5:       |                                                                 ^~~~~
warning: scx_lavd@1.0.5: src/bpf/main.bpf.c:383:68: note: passing argument to parameter 'taskc' here
warning: scx_lavd@1.0.5:   383 | static u64 calc_time_slice(struct task_struct *p, struct task_ctx *taskc)
warning: scx_lavd@1.0.5:       |                                                                    ^
warning: scx_lavd@1.0.5: src/bpf/main.bpf.c:1385:26: warning: incompatible pointer types passing 'struct task_struct *' to parameter of type 'struct task_ctx *' [-Wincompatible-pointer-types]
warning: scx_lavd@1.0.5:  1385 |                 reset_lock_futex_boost(taskc, cpuc);
warning: scx_lavd@1.0.5:       |                                        ^~~~~
warning: scx_lavd@1.0.5: src/bpf/lock.bpf.c:96:53: note: passing argument to parameter 'taskc' here
warning: scx_lavd@1.0.5:    96 | static void reset_lock_futex_boost(struct task_ctx *taskc, struct cpu_ctx *cpuc)
warning: scx_lavd@1.0.5:       |                                                     ^
warning: scx_lavd@1.0.5: src/bpf/main.bpf.c:1398:18: warning: incompatible pointer types passing 'struct task_struct *' to parameter of type 'struct task_ctx *' [-Wincompatible-pointer-types]
warning: scx_lavd@1.0.5:  1398 |         if (is_eligible(p_run))
warning: scx_lavd@1.0.5:       |                         ^~~~~
warning: scx_lavd@1.0.5: src/bpf/util.bpf.c:248:42: note: passing argument to parameter 'taskc' here
warning: scx_lavd@1.0.5:   248 | static bool is_eligible(struct task_ctx *taskc)
warning: scx_lavd@1.0.5:       |                                          ^
warning: scx_lavd@1.0.5: src/bpf/main.bpf.c:1398:6: warning: variable 'cpuc_run' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
warning: scx_lavd@1.0.5:  1398 |         if (is_eligible(p_run))
warning: scx_lavd@1.0.5:       |             ^~~~~~~~~~~~~~~~~~
warning: scx_lavd@1.0.5: src/bpf/main.bpf.c:1424:31: note: uninitialized use occurs here
warning: scx_lavd@1.0.5:  1424 |                 try_decrease_cpuperf_target(cpuc_run);
warning: scx_lavd@1.0.5:       |                                             ^~~~~~~~
warning: scx_lavd@1.0.5: src/bpf/main.bpf.c:1398:2: note: remove the 'if' if its condition is always false
warning: scx_lavd@1.0.5:  1398 |         if (is_eligible(p_run))
warning: scx_lavd@1.0.5:       |         ^~~~~~~~~~~~~~~~~~~~~~~
warning: scx_lavd@1.0.5:  1399 |                 goto update_cpuperf;
warning: scx_lavd@1.0.5:       |                 ~~~~~~~~~~~~~~~~~~~
warning: scx_lavd@1.0.5: src/bpf/main.bpf.c:1391:26: note: initialize the variable 'cpuc_run' to silence this warning
warning: scx_lavd@1.0.5:  1391 |         struct cpu_ctx *cpuc_run;
warning: scx_lavd@1.0.5:       |                                 ^
warning: scx_lavd@1.0.5:       |                                  = NULL
warning: scx_lavd@1.0.5: 6 warnings generated.
   Compiling scx_rustland v1.0.5 (/data/users/jakehillion/scx/scheds/rust/scx_rustland)
   Compiling scx_rlfifo v1.0.5 (/data/users/jakehillion/scx/scheds/rust/scx_rlfifo)
warning: scx_rustland@1.0.5: main.bpf.c:857:6: warning: unused variable 'cpu' [-Wunused-variable]
warning: scx_rustland@1.0.5:   857 |         s32 cpu;
warning: scx_rustland@1.0.5:       |             ^~~
warning: scx_rustland@1.0.5: main.bpf.c:104:13: warning: unused function 'set_cpu_state' [-Wunused-function]
warning: scx_rustland@1.0.5:   104 | static bool set_cpu_state(struct bpf_cpumask *cpumask, s32 cpu, bool state)
warning: scx_rustland@1.0.5:       |             ^~~~~~~~~~~~~
warning: scx_rustland@1.0.5: main.bpf.c:382:12: warning: unused function 'dsq_to_cpu' [-Wunused-function]
warning: scx_rustland@1.0.5:   382 | static s32 dsq_to_cpu(u64 dsq_id)
warning: scx_rustland@1.0.5:       |            ^~~~~~~~~~
warning: scx_rustland@1.0.5: 3 warnings generated.
warning: scx_rlfifo@1.0.5: main.bpf.c:857:6: warning: unused variable 'cpu' [-Wunused-variable]
warning: scx_rlfifo@1.0.5:   857 |         s32 cpu;
warning: scx_rlfifo@1.0.5:       |             ^~~
warning: scx_rlfifo@1.0.5: main.bpf.c:104:13: warning: unused function 'set_cpu_state' [-Wunused-function]
warning: scx_rlfifo@1.0.5:   104 | static bool set_cpu_state(struct bpf_cpumask *cpumask, s32 cpu, bool state)
warning: scx_rlfifo@1.0.5:       |             ^~~~~~~~~~~~~
warning: scx_rlfifo@1.0.5: main.bpf.c:382:12: warning: unused function 'dsq_to_cpu' [-Wunused-function]
warning: scx_rlfifo@1.0.5:   382 | static s32 dsq_to_cpu(u64 dsq_id)
warning: scx_rlfifo@1.0.5:       |            ^~~~~~~~~~
warning: scx_rlfifo@1.0.5: 3 warnings generated.
    Finished `release` profile [optimized] target(s) in 3.79s
```

**Comment by htejun** [comment]
We had `-Werror` on for a while but that didn't work out because different compiler versions warn on different things and there sometimes are cases where the resolution to satisfy all compilers isn't straightforward or even possible.

I don't really care how it's presented but being able to see bpf build warnings during regular builds would be really great.

**Pull request merged**
