### PR TITLE
rust Updated libbpf-rs & libbpf-cargo to 0.24

### PR DESCRIPTION
**Pull request by danielocfb**
Use updated libbpf-rs & libbpf-cargo. Generated skeletons now contain directly accessible map and program objects, no longer necessitating the use of accessor methods. As a result, the risk for mutability conflicts is reduced greatly.

### CODE REVIEW

**Comment by danielocfb** [comment]
Not going to un-draft this until the next `libbpf-rs` release is cut (which could take a while). We could land it as-is conceptually, but I suspect you guys don't want to depend on a random `libbpf-rs` snapshot, as that would block any attempt of publishing your crates.

**Comment by danielocfb** [comment]
> Not going to un-draft this until the next `libbpf-rs` release is cut

`0.24.0` is out, so I think this change can be reviewed now.

**Review by arighi — APPROVED** [review]

**Comment by danielocfb** [comment]
Please wait with merge a little longer. Still investigating a potential issue.

**Comment by danielocfb** [comment]
> Please wait with merge a little longer. Still investigating a potential issue.

We should be good now.

**Comment by htejun** [comment]
FYI, @danielocfb for some reason, your commit's commit date is earlier than its parent and `tig` has trouble rendering it correctly.

**Pull request merged**
