### PR TITLE
scx_utils: Fix linter errors

### PR DESCRIPTION
**Pull request by frelon**
Fix linter errors using `cargo fmt`

Signed-off-by: Fredrik Lönnegren <fredrik.lonnegren@suse.com>

### CODE REVIEW

**Comment by htejun** [comment]
I wonder whether this is just a different version of `cargo` being used. @JakeHillion, aren't we auto-formatting everything now?

**Comment by hodgesds** [comment]
I think there is some noise in the linter test from some changes in the loader, see the test [failures](https://github.com/sched-ext/scx/actions/runs/11040959192/job/30670157058?pr=689). It might be from using [nightly](https://github.com/sched-ext/scx/blob/main/.github/workflows/caching-build.yml#L25) for `cargo fmt`.

**Comment by likewhatevs** [comment]
The command is `cargo +nightly-2024-09-10 fmt` (presuming cargo was installed via rustup or rustup is installed), I have another PR which runs that for the whole repo (it needs that atm to make ci signal green).

**Comment by frelon** [comment]
I see, looks like this is already merged in #691, thanks!

**Comment by JakeHillion** [comment]
Thanks folks for bringing this check back in line. @likewhatevs is right, you need a specific version. When I enabled this I found that we needed nightly cargo/rustfmt for this to work, the ordinary version complained a lot, hence the pinning to a specific version of nightly in an effort for stability. The downside is everyone needs to have the identical version, alternatively you can copy the patch provided in the CI failure and apply it with `cat | patch -p1`.

Now this check has been okay for a while I'll make it a requirement on PRs, slightly more work for contributors but it'll keep it clean in future.

**Comment by htejun** [comment]
@JakeHillion can you document how to configure cargo to make it format the same way? Can that be a part of the repo itself maybe?

**Pull request closed without merging**
