### PR TITLE
scx_rusty: handle gracefully tasks without context in dom_xfer_task()

### PR DESCRIPTION
**Pull request by arighi**
Make dom_xfer_task() static to satisfy the verifier regarding the use of the task_ctx pointer.

Then pass the task context directly as a pointer to dom_xfer_task() to eliminates the need for task and task context lookups from the PID, which can fail if the task context lookup from the PID is unsuccessful (due to racy behavior).

This seems to fix failures with scx_rusty in our CI.

### CODE REVIEW

**Comment by arighi** [comment]
Hm.. nevermind, it's still failing, will take a look later, I may have done something silly.

**Comment by htejun** [comment]
The unreliable behavior is probably from #610.

**Comment by arighi** [comment]
Right, the "pid" logic introduces a bunch of potential issues and the fix is not so trivial. I opened this, because our CI seems to fail reliably because of this, but I wasn't able to reproduce it locally (for some reasons it seems to happen only inside the github action...). I'll investigate more to see if we can find a better reproducer (probably after LPC), let's put this on hold for now.

**Comment by htejun** [comment]
Closing for now. Please feel free to reopen if necessary.

**Pull request closed without merging**
